
workDir: /home/wangyang/workspace/nextflow-java-api/workDir
scriptDir: /home/wangyang/workspace/nextflow-java-api/workDir
giteaUrl: http://192.168.10.178:3000
spring:
  security:
    user:
      name: shanjun
      password: shanjunshanjun
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test-api

server:
  servlet:
    context-path: /pipeline
